// actions for signin with email and password
export const SIGN_IN_WITH_EMAIL_INIT = "SIGN_IN_WITH_EMAIL_INIT";
export const SIGN_IN_WITH_EMAIL_SUCCESS = "SIGN_IN_WITH_EMAIL_SUCCESS";
export const SIGN_IN_WITH_EMAIL_FAILED = "SIGN_IN_WITH_EMAIL_FAILED";

// actions for signup with email and password
export const SIGN_UP_WITH_EMAIL_INIT = "SIGN_UP_WITH_EMAIL_INIT";
export const SIGN_UP_WITH_EMAIL_SUCCESS = "SIGN_UP_WITH_EMAIL_SUCCESS";
export const SIGN_UP_WITH_EMAIL_FAILED = "SIGN_UP_WITH_EMAIL_FAILED";

// actions for signin with google
export const SIGN_IN_WITH_GOOGLE_INIT = "SIGN_IN_WITH_GOOGLE_INIT";
export const SIGN_IN_WITH_GOOGLE_SUCCESS = "SIGN_IN_WITH_GOOGLE_SUCCESS";
export const SIGN_IN_WITH_GOOGLE_FAILED = "SIGN_IN_WITH_GOOGLE_FAILED";

// actions for signout
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";

// set auth data bu firebase observer method
export const SET_AUTH_DATA = "SET_AUTH_DATA";

// actions for creating posts
export const CREATE_POST_INIT = "CREATE_POST_INIT";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILED = "CREATE_POST_FAILED";

// action for fetching posts
export const FETCH_POSTS_INIT = "FETCH_POSTS_INIT";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";

// actions for updating the posts
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";

// actions for fecthing nearbys
export const FETCH_NEARBY_DONORS = "FETCH_NEARBY_DONORS";
export const FETCH_NEARBY_RECEIVERS = "FETCH_NEARBY_RECEIVERS";
export const FETCH_NEARBY_HOSPITALS = "FETCH_NEARBY_HOSPITALS";

// action for contacting to those nearbys
export const CONTACT_TO = "CONTACT_TO";
export const VISIT = "VISIT";

// all these below actions are related to profile module
export const SET_EMPTY_PROFILE_INIT = "SET_EMPTY_PROFILE_INIT";
export const SET_EMPTY_PROFILE_SUCCESS = "SET_EMPTY_PROFILE_SUCCESS";
export const SET_EMPTY_PROFILE_FAILED = "SET_EMPTY_PROFILE_FAILED";

export const LOAD_PROFILE_ON_SIGNIN_INIT = "LOAD_PROFILE_ON_SIGNIN_INIT";
export const LOAD_PROFILE_ON_SIGNIN_SUCCESS = "LOAD_PROFILE_ON_SIGNIN_SUCCESS";
export const LOAD_PROFILE_ON_SIGNIN_FAILED = "LOAD_PROFILE_ON_SIGNIN_FAILED";

export const SET_PROFILE_REALTIME = "SET_PROFILE_REALTIME";

export const LOAD_PROFILE_ON_REFRESH_INIT = "LOAD_PROFILE_ON_REFRESH_INIT";
export const LOAD_PROFILE_ON_REFRESH_SUCCESS = "LOAD_PROFILE_ON_REFRESH_SUCCESS";
export const LOAD_PROFILE_ON_REFRESH_FAILED = "LOAD_PROFILE_ON_REFRESH_FAILED";

export const VANISH_PROFILE_ON_SIGNOUT = "VANISH_PROFILE_ON_SIGNOUT";

export const UPDATE_PROFILE_DATA_INIT = "UPDATE_PROFILE_DATA_INIT";
export const UPDATE_PROFILE_DATA_SUCCESS = "UPDATE_PROFILE_DATA_SUCCESS";
export const UPDATE_PROFILE_DATA_FAILED = "UPDATE_PROFILE_DATA_FAILED";






